import "./globals.css"
import "normalize.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="w-full 2xl:max-w-screen-xl mx-auto">{children}</body>
    </html>
  )
}
